### ISSUE TITLE
how to use in Tampermonkey/Geasemonkey ?

### ISSUE THREAD

**Issue by laomo** [tactivos/jquery-sew#14]
tips:Object [object Object] has no method 'sew'

**Comment by santiagotactivos** [comment]
Hi,  I don't understand what you mean, I've never used Tampermonkey

**Comment by laomo** [comment]
I'm sorry. There is no problem. It's my fault. just need @require,like this:
// @require http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js
// @require http://jquery-sew.s3-website-us-east-1.amazonaws.com/jquery.sew.js
// @require http://jquery-sew.s3-website-us-east-1.amazonaws.com/jquery.caretposition.js

@santiagotactivos Tampermonkey is a manager of userscripts for Chrome.
